config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'email/new'

  root 'welcome#index'

  post 'email/new' => 'email#create'

  resources :user, except: :destroy

  resources :email, except: :destroy

end

app/models/email.rb
class Email < ActiveRecord::Base
  validates :user, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :emails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def new
    @user  = User.new
    @email = Email.new
  end

  def create
    @user  = User.create(user_params)
    @email = Email.create(body: email_params[:body], user_id: @user.id)

    respond_to do |format|
      if @user.save && @email.save
        #onSuccessful save and send email
        UserMailer.thanks_email(@user).deliver_now

        #send email to admin with new user details
        AdminMailer.new_user(@user, @email).deliver_now

        format.html { redirect_to(root_path, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :phone, :street, :zip, :emailaddress)
  end

  def email_params
    params.require(:email).permit(:body)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="nav-wrapper page-footer" style="margin-top:0px;">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Who we are.</h5>
        <div class="col l4">
          <%= image_tag 'Family-Stock-Photo.jpg', class:'circle responsive-img' %>
        </div>
        <div class="col l8">
          <p>We are a small verteran-owned company located in Lake City, Florida. We pride ourselves in providing affordable and premium lawncare services to the Lake City area.</p>
          <p>Phone: (256) 504 - 9182.</p>
          <p>Email: <%= link_to "kevinmlipscomb@gmail.com", email_new_path, class:'hyperlink-footer'%></p>
        </div>
      </div>
      <!-- <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div> -->
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <nav role="navigation">
      <div class="container nav-wrapper">
        <a style="padding-top:4px;" href="/" class="brand-logo" data-no-turbolink><%= image_tag 'logos/daograss.png' %></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="sass.html">Schedule</a></li>
          <li><%= link_to 'Contact Us', email_new_path %></li>
          <li><a href="javascript.html">Rates</a></li>
          <li><a href="javascript.html">Sign In</a></li>
          <li>|</li>
          <li><a href="javascript.html">Register</a></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DAO Lawns & More</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br>
      <br>
      <div class="row"><h1 class="header right white-text">DAO Lawns & More</h1></div>
      <h4 class="header right white-text">Edging | Mowing | Trimming</h4>
    </div>
    <div class="parallax"> <%= image_tag 'image4729.png' %> </div>
  </div>
</div>
<div class="primary-light-background">
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center"><i class="mdi-content-content-cut"></i></h2>
            <h5>Quality Service</h5>
            <p class="light">We offer a variety of quality services to meet your lawncare needs. Our services include edging, mowing, trimming, hedging, pruning, and rubbish removal to name a few.</p>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center"><i class="mdi-editor-attach-money"></i></h2>
            <h5>Affordable</h5>
            <p class="light">By offerring free estimates, we aim to provide you with valuable services without surprises. <%= link_to "Contact us", email_new_path, class:"light" %> today to schedule an appointment, or request a free estimate.</p>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center"><i class="mdi-action-home"></i></h2>
            <h5>Local</h5>
            <p class="light">We are a small veteran-owned company based out of Lake City, Florida providing lawncare services to the Lake City Area.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="parallax-container">
  <div class="section no-pad-bot">
  <div class="container">
    <div class="caption center-align">
      <div class="row"><h1 class="left white-text">Veteran Owned</h1></div>
      <h4 class="left white-text">Community Focused</h4>
    </div>
    </div>
    <div class="parallax"> <%= image_tag 'image4582.png' %> </div>
  </div>
</div>